// Omarctalia editorial descriptions, keyed by Omarchy menu ID.
// Explicit descriptions from menu definitions and app desktop entries win.
var descriptions = {
    "install.gaming.minecraft": "Install and open the Minecraft launcher",
    "install.gaming.heroic": "Install a launcher for Epic, GOG, and Amazon games",
    "install.gaming.lutris": "Install Lutris with tools for running Windows games",
    "install.gaming.battlenet": "Install Battle.net with compatibility tools for Windows games",
    "install.gaming.xbox-cloud": "Add Xbox Cloud Gaming as a web application",
    "install.gaming.geforce-now": "Install and open NVIDIA GeForce NOW cloud gaming",
    "install.gaming.retroarch": "Install RetroArch and its collection of game emulators",
    "install.gaming.steam": "Install Steam and the graphics drivers for this computer",
    "install.ai.ollama": "Install Ollama with support for the detected GPU",
    "install.ai.openclaw": "Install the OpenClaw agent platform and its control interface",
    "install.ai.hermes": "Install the Hermes desktop application",
    "install.ai.t3-code": "Install T3 Code and apply the Omarchy color palette",
    "install.ai.chatgpt": "Install the ChatGPT desktop application",
    "install.service.bitwarden": "Install Bitwarden password management tools",
    "install.service.nordvpn": "Install NordVPN with an optional graphical interface",
    "install.service.tailscale": "Install Tailscale to connect devices over a private network",
    "install.service.signal": "Install Signal for private messaging and calls",
    "install.service.spotify": "Install Spotify for music and podcasts",
    "install.service.dropbox": "Install and start Dropbox file synchronization",
    "install.service.1password": "Install the password manager and its Chromium extension",
    "apps": "Find and launch your installed applications",
    "learn": "Browse manuals, keyboard shortcuts, and community help",
    "trigger": "Capture, share, set reminders, and toggle desktop features",
    "style": "Personalize themes, wallpaper, fonts, and desktop appearance",
    "setup": "Configure displays, input, default apps, and security",
    "install": "Add applications, development tools, themes, and services",
    "remove": "Uninstall applications, tools, and optional system features",
    "update": "Update software, restart services, and restore settings",
    "about": "View Omarchy version and system information",
    "system": "Lock, sleep, sign out, restart, or shut down your computer",
    "system.screensaver": "Start the screensaver now",
    "system.lock": "Lock your session and require authentication to return",
    "system.suspend": "Put the computer to sleep while keeping your session",
    "system.hibernate": "Save your session to disk and power down",
    "system.logout": "End your desktop session and return to the login screen",
    "system.reboot": "Restart the computer",
    "system.shutdown": "Turn off the computer",
    "learn.keybindings": "Look up Omarchy keyboard shortcuts",
    "learn.omarchy": "Read the Omarchy user manual",
    "learn.hyprland": "Open the Hyprland window manager documentation",
    "learn.arch": "Search the Arch Linux wiki for system guides and help",
    "learn.neovim": "Look up LazyVim editor shortcuts",
    "learn.bash": "Open a reference for Bash shell commands and syntax",
    "learn.tmux-keybindings": "Look up shortcuts for tmux terminal sessions",
    "learn.herdr-keybindings": "Look up Herdr keyboard shortcuts",
    "learn.community": "Open the Omarchy community on Discord",
    "trigger.emoji": "Find an emoji to insert into your text",
    "trigger.reminder": "Create, view, or clear reminders",
    "trigger.reminder.set": "Set a reminder with a message and time",
    "trigger.reminder.show": "View your scheduled reminders",
    "trigger.reminder.clear": "Clear all scheduled reminders",
    "trigger.capture": "Take screenshots, record video, or extract text and colors",
    "trigger.capture.screenshot": "Capture a screenshot of your screen or a selected area",
    "trigger.capture.screenrecord": "Choose the audio and camera options for a screen recording",
    "trigger.capture.screenrecord.stop": "Stop the current screen recording",
    "trigger.capture.screenrecord.no-audio": "Record your screen without sound",
    "trigger.capture.screenrecord.desktop-audio": "Record your screen and application audio",
    "trigger.capture.screenrecord.microphone": "Record your screen, application audio, and microphone",
    "trigger.capture.screenrecord.webcam": "Record your screen with webcam, desktop audio, and microphone",
    "trigger.capture.text": "Recognize and copy text from an area of the screen",
    "trigger.capture.qr": "Read a QR code displayed on your screen",
    "trigger.capture.color": "Pick a color from the screen and copy its value",
    "trigger.transcode": "Convert media files to another format",
    "trigger.share": "Send clipboard content, files, or folders to another device",
    "trigger.share.clipboard": "Share the current clipboard content",
    "trigger.share.file": "Choose a file to share",
    "trigger.share.folder": "Choose a folder to share",
    "trigger.share.receive": "Open LocalSend to receive files from nearby devices",
    "trigger.toggle": "Turn desktop conveniences on or off",
    "trigger.hardware": "Control displays, graphics, touchpad, and touchscreen",
    "trigger.hardware.laptop-display": "Turn the laptop's built-in display on or off",
    "trigger.hardware.mirror-display": "Toggle mirroring of the laptop display",
    "trigger.hardware.hybrid-gpu": "Change the graphics mode on a hybrid-GPU laptop",
    "trigger.hardware.touchpad": "Enable or disable the touchpad",
    "trigger.hardware.touchpad-haptics": "Choose how strongly the touchpad responds to clicks",
    "trigger.hardware.touchpad-haptics.low": "Use light touchpad click feedback",
    "trigger.hardware.touchpad-haptics.mid": "Use medium touchpad click feedback",
    "trigger.hardware.touchpad-haptics.high": "Use strong touchpad click feedback",
    "trigger.hardware.touchscreen": "Enable or disable touchscreen input",
    "trigger.toggle.idle-lock": "Toggle automatic idle behavior to keep the desktop awake",
    "trigger.toggle.notifications": "Silence notifications or allow them again",
    "trigger.toggle.crash-capture": "Enable or disable capture of application crash reports",
    "trigger.toggle.screensaver": "Enable or disable the automatic screensaver",
    "trigger.toggle.nightlight": "Toggle warmer screen colors for evening use",
    "trigger.toggle.top-bar": "Show or hide the desktop menu bar",
    "trigger.toggle.battery-percentage": "Show or hide the battery percentage in the bar",
    "trigger.toggle.workspace-layout": "Switch the current workspace's window layout",
    "trigger.toggle.window-gaps": "Toggle spacing between tiled windows",
    "trigger.toggle.one-window-ratio": "Toggle the proportions of a single tiled window",
    "trigger.tests": "Measure network speed or disk performance",
    "trigger.tests.network-speedtest": "Measure your network connection speed",
    "trigger.tests.disk-speedtest": "Measure disk read and write performance",
    "style.theme": "Choose a color theme for the desktop and applications",
    "style.background": "Choose a wallpaper from the current theme",
    "style.unlock": "Choose the boot-time disk unlock screen appearance",
    "style.font": "Choose the desktop's monospace font",
    "style.bar": "Change the menu bar's position and transparency",
    "style.bar.position": "Choose which screen edge holds the menu bar",
    "style.bar.transparency": "Toggle the menu bar's transparent background",
    "style.hyprland": "Edit window borders, gaps, animations, and other visual settings",
    "style.screensaver": "Customize the artwork shown by the screensaver",
    "style.about": "Customize the artwork shown in the About screen",
    "style.about.text": "Edit the About screen's text artwork",
    "style.about.image": "Create About screen artwork from an image",
    "style.about.default": "Restore the default About screen artwork",
    "style.screensaver.text": "Edit the screensaver's text artwork",
    "style.screensaver.image": "Create screensaver artwork from an image",
    "style.screensaver.default": "Restore the default screensaver artwork",
    "setup.monitors": "Edit display arrangement, resolution, refresh rate, and scaling",
    "setup.keybindings": "Edit your custom keyboard shortcuts",
    "setup.input": "Edit keyboard, mouse, and touchpad settings",
    "setup.network": "Configure name resolution or share your Wi-Fi connection details",
    "setup.network.dns": "Choose which DNS service resolves website addresses",
    "setup.network.dns.dhcp": "Use the DNS servers supplied by your network",
    "setup.network.dns.cloudflare": "Use Cloudflare's DNS servers",
    "setup.network.dns.google": "Use Google's DNS servers",
    "setup.network.dns.custom": "Enter your own DNS server addresses",
    "setup.network.qr": "Show a QR code for joining your current Wi-Fi network",
    "setup.default": "Choose which apps open links, files, terminals, and agent sessions",
    "setup.default.agent": "Choose the AI agent launched by Omarchy",
    "setup.default.browser": "Choose the browser used to open web links",
    "setup.default.terminal": "Choose the terminal used by Omarchy launchers",
    "setup.default.editor": "Choose the editor used to open text and configuration files",
    "setup.plugin": "Add, enable, disable, clone, or remove shell plugins",
    "setup.plugin.enable": "Choose an installed plugin to activate",
    "setup.plugin.disable": "Turn off a plugin without uninstalling it",
    "setup.plugin.add": "Install a shell plugin from a source repository",
    "setup.plugin.clone": "Make a personal copy of a plugin to customize",
    "setup.plugin.remove": "Uninstall a user-installed shell plugin",
    "setup.security": "Configure authentication, remote login, and privileged access",
    "setup.security.fingerprint": "Set up fingerprint authentication",
    "setup.security.fido2": "Set up authentication with a physical security key",
    "setup.security.sshd": "Set up the SSH server for remote access to this computer",
    "setup.security.passwordless-sudo": "Configure running administrator commands without a password",
    "setup.security.sudoless-docker": "Allow Docker commands without using sudo",
    "setup.config": "Open configuration files for the desktop and input tools",
    "setup.config.hyprland": "Edit the main Hyprland configuration file",
    "setup.config.hyprsunset": "Edit the night-light schedule and color temperature",
    "setup.config.xcompose": "Edit Compose-key sequences for entering special characters",
    "setup.direct-boot": "Configure a firmware entry to boot Omarchy directly",
    "setup.reset": "Restore the factory state, removing user data and customizations",
    "install.package": "Find and install software from the package repositories",
    "install.aur": "Find and install community packages from the Arch User Repository",
    "install.webapp": "Add a website as an application with its own launcher",
    "install.tui": "Add a terminal application to the app launcher",
    "install.style": "Add themes, wallpaper, and fonts",
    "install.style.theme": "Install a theme from a repository",
    "install.style.background": "Add a wallpaper image to your collection",
    "install.style.font": "Install an additional monospace font",
    "install.service": "Add communication, password, sync, and networking applications",
    "install.development": "Install language runtimes, frameworks, and development tools",
    "install.editor": "Install an editor for code and text files",
    "install.terminal": "Install another terminal emulator",
    "install.browser": "Install another web browser",
    "install.ai": "Add AI assistants, local models, and voice dictation",
    "install.gaming": "Install game stores, emulators, and controller support",
    "install.windows": "Set up Windows in a virtual machine",
    "install.preinstalls": "Install Omarchy's bundled optional applications",
    "install.service.once": "Install ONCE, enable its background service, and open it",
    "install.service.chromium-account": "Set up Google account integration for Chromium",
    "install.ai.dictation": "Install voice dictation for entering text by speaking",
    "install.development.docker-dbs": "Set up databases running in Docker containers",
    "install.gaming.xbox-controllers": "Install support for Bluetooth Xbox controllers",
    "install.gaming.retro-launcher": "Add a RetroArch game to the application launcher",
    "remove.package": "Choose installed packages to uninstall",
    "remove.webapp": "Remove a website's application launcher",
    "remove.tui": "Remove a terminal application's launcher entry",
    "remove.development": "Remove installed language runtimes and development tools",
    "remove.theme": "Choose an installed theme to remove",
    "remove.browser": "Choose an installed web browser to uninstall",
    "remove.dictation": "Uninstall voice dictation support",
    "remove.gaming": "Remove game stores, emulators, and gaming integrations",
    "remove.service": "Uninstall optional sync and networking services",
    "remove.windows": "Remove the Windows virtual machine",
    "remove.preinstalls": "Remove Omarchy's bundled optional applications",
    "remove.security": "Remove optional authentication and access features",
    "remove.security.fingerprint": "Remove fingerprint authentication support",
    "remove.security.fido2": "Remove physical security-key authentication support",
    "remove.security.sshd": "Disable remote SSH login and close its firewall port",
    "remove.security.sudoless-docker": "Require sudo again for Docker commands",
    "remove.gaming.xbox-controllers": "Remove Bluetooth Xbox controller support",
    "remove.ai": "Choose an installed AI application to uninstall",
    "update.omarchy": "Update Omarchy and installed system packages",
    "update.channel": "Choose the Omarchy release channel used for updates",
    "update.channel.stable": "Use stable Omarchy releases",
    "update.channel.rc": "Try release candidates before the next stable release",
    "update.channel.edge": "Use the latest edge-channel updates",
    "update.channel.dev": "Use development-channel updates",
    "update.config": "Restore selected configuration files to Omarchy defaults",
    "update.themes": "Update additional themes installed from repositories",
    "update.process": "Restart desktop services",
    "update.process.hyprsunset": "Restart the night-light service",
    "update.process.shell": "Restart the menu bar, notifications, and desktop shell",
    "update.hardware": "Restart audio, wireless, Bluetooth, or trackpad services",
    "update.hardware.audio": "Restart the audio services to reconnect sound devices",
    "update.hardware.wifi": "Restart Wi-Fi networking",
    "update.hardware.bluetooth": "Restart Bluetooth connectivity",
    "update.hardware.trackpad": "Restart trackpad support",
    "update.firmware": "Check for and install device firmware updates",
    "update.password": "Change your login or disk-encryption password",
    "update.password.drive": "Change the password used to unlock the encrypted drive",
    "update.password.user": "Change your user account's login password",
    "update.timezone": "Choose the system's time zone",
    "update.time": "Restart synchronization of the system clock"
};

function describe(entry) {
    if (!entry) return "";
    if (entry.description) return entry.description;
    if (entry.kind === "app") return "";
    var id = String(entry.id || "");
    var label = String(entry.label || id);
    if (descriptions[id]) return descriptions[id];
    if (entry.providerMenu === "style.font") return "Use " + label.replace(/^✓\s*/, "") + " as the desktop font";
    if (entry.providerMenu && entry.providerMenu.indexOf("power") >= 0)
        return "Switch to the " + label + " power profile";
    if (id.indexOf("style.bar.position.") === 0)
        return "Move the menu bar to the " + label.toLowerCase() + " edge of the screen";
    var defaults = id.match(/^setup\.default\.(agent|browser|terminal|editor)\./);
    if (defaults) return "Use " + label + " as the default " + (defaults[1] === "agent" ? "AI agent" : defaults[1]);
    var operation = id.match(/^(install|remove)\.(development|browser|terminal|editor|service|gaming|ai|style\.font)\./);
    if (operation) {
        var verb = operation[1] === "install" ? "Install " : "Uninstall ";
        if (entry.kind === "menu" || entry.kind === "link")
            return "Choose " + label + " tools to " + (operation[1] === "install" ? "install" : "remove");
        var suffix = {development: " development tools", browser: " web browser", terminal: " terminal emulator", editor: " text editor", "style.font": " font"}[operation[2]] || "";
        return verb + label + suffix;
    }
    if (id.indexOf("update.config.") === 0)
        return "Restore " + label + " configuration to Omarchy defaults";
    // Future or user-defined items keep an honest fallback; no guesses about commands.
    return entry.kind === "menu" || entry.kind === "link" ? "Browse " + label + " options" : "Run " + label;
}
